spring.application.name=talentmetricsAI-backend

server.port=8080

spring.output.ansi.enabled=ALWAYS

logging.level.org.springframework.security=DEBUG

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tm_database
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=secretito-de-minimo-32-caracteres-para-firmar-tokens
# 10 min
jwt.expiration=600000
# 12 horas
jwt.refresh-expiration=43200000

# React frontend url
cors.allowed-origins=http://localhost:3000

# LDAP Configuration
spring.ldap.urls=ldap://localhost:389
spring.ldap.base=dc=capitalhumano,dc=com
# Permisos para consultar el directorio LDAP
spring.ldap.username=cn=admin,dc=capitalhumano,dc=com
spring.ldap.password=admin
